name: smartpaisaa
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  smswatcher: ^0.0.2
  sqflite: ^2.3.3
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  path: ^1.9.0
  intl: ^0.18.0
  crypto: ^3.0.3
  # File operations
  path_provider: ^2.1.1
  share_plus: ^7.2.1
#  carousel_slider: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
